typography_spectrum: 0.026720255613327026
color:
  brandStrength: 0.7398983337916434
  lightness: 0.10545821487903595
  saturation: 0.5299996356479824
  rhythmicContrast: 0.9070120609831065
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
layout_spectrum: 0.04299527918919921
author:
  name: Kim V. Diaz
name: Demand Grand
navigation:
  - name: Store Front
    url: 'http://demandgrand.etsy.com'
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/demandgrand'
    type: external
  - name: Make Contact
    url: 'mailto:demandgrand@gmail.com'
    type: external
  - name: Our Pinterest Boards
    url: 'https://www.pinterest.com/demandgrand/'
    type: external
title: Demand Grand
description: because life's milestone's are far from boring
